[tool.poetry]
name = "aigenml"
version = "0.1.0"
description = ""
authors = ["Kailash <ahikailash1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorflow = "2.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
