"""empty message

Revision ID: a31cd9e949fc
Revises: 
Create Date: 2023-03-07 20:34:58.314518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31cd9e949fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ainft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('dataCid', sa.String(), nullable=True),
    sa.Column('metadataCid', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('tokenId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fileName')
    )
    op.create_table('ainft_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_dir', sa.String(), nullable=True),
    sa.Column('no_of_ainfts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ainft_project')
    op.drop_table('ainft')
    # ### end Alembic commands ###
